# Generated by Django 3.0.4 on 2020-04-08 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_project', '0003_auto_20200408_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_dete',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 14, 50, 38, 989504, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='created_dete',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 14, 50, 38, 986508, tzinfo=utc)),
        ),
    ]
