# Generated by Django 3.0.4 on 2020-04-08 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_project', '0004_auto_20200408_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_dete',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 14, 52, 48, 574582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 14, 52, 48, 576576, tzinfo=utc)),
        ),
    ]
